### ISSUE TITLE
NODE.YML Le faltan uses para deploy en Heroku

### ISSUE THREAD

**Issue by SoniaSayago** [Laboratoria/REG003-chat-app#2]
Sumamos este  comando de uses extra para deployar el proyecto en el node.yml.
Check

```
- uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "slack-chats" #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
```
